import React, { useState, useMemo } from 'react';
import { Plus, Edit2, Trash2, ChevronUp, ChevronDown, Search } from 'lucide-react';
import { FleetData, Tour } from '../types';
import { showSuccess } from '../utils/toast'; // Import toast utilities
import { formatDate } from '../utils/date'; // Import the new utility
import ConfirmDialog from './ConfirmDialog'; // Import ConfirmDialog
import { Button } from './ui/button'; // Import shadcn Button

interface ToursProps {
  data: FleetData;
  userRole: 'admin' | 'direction' | 'utilisateur';
  onAdd: (tour: Omit<Tour, 'id' | 'user_id' | 'created_at'>) => void;
  onUpdate: (tour: Tour) => void;
  onDelete: (id: string) => void;
}

const Tours: React.FC<ToursProps> = ({ data, onAdd, onUpdate, onDelete }) => {
  const [showModal, setShowModal] = useState(false);
  const [editingTour, setEditingTour] = useState<Tour | null>(null);
  const [showConfirmDialog, setShowConfirmDialog] = useState(false);
  const [tourToDelete, setTourToDelete] = useState<string | null>(null);

  // State for filtering, sorting, and pagination
  const [searchTerm, setSearchTerm] = useState('');
  const [sortColumn, setSortColumn] = useState<keyof Tour>('date');
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc');
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 10; // You can adjust this value

  // Filtered and sorted data
  const filteredAndSortedTours = useMemo(() => {
    let filtered = data.tours.filter(tour => {
      const vehicle = data.vehicles.find(v => v.id === tour.vehicle_id);
      const driver = data.drivers.find(d => d.id === tour.driver_id);
      
      return (
        tour.date.toLowerCase().includes(searchTerm.toLowerCase()) ||
        (vehicle?.plate || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
        (driver?.name || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
        tour.status.toLowerCase().includes(searchTerm.toLowerCase())
      );
    });

    filtered.sort((a, b) => {
      const aValue = a[sortColumn];
      const bValue = b[sortColumn];

      // Handle null/undefined values first
      if (aValue === null || aValue === undefined) {
        return sortDirection === 'asc' ? -1 : 1; // Null/undefined comes first in asc, last in desc
      }
      if (bValue === null || bValue === undefined) {
        return sortDirection === 'asc' ? 1 : -1; // Null/undefined comes first in asc, last in desc
      }

      // Now that we know values are not null/undefined, compare them based on type
      if (typeof aValue === 'string' && typeof bValue === 'string') {
        return sortDirection === 'asc' ? aValue.localeCompare(bValue) : bValue.localeCompare(aValue);
      }
      if (typeof aValue === 'number' && typeof bValue === 'number') {
        return sortDirection === 'asc' ? aValue - bValue : bValue - aValue;
      }
      // Fallback for any other unexpected types (should not be reached with current Tour interface)
      return 0;
    });
    return filtered;
  }, [data.tours, data.vehicles, data.drivers, searchTerm, sortColumn, sortDirection]);

  // Paginated data
  const totalPages = Math.ceil(filteredAndSortedTours.length / itemsPerPage);
  const currentTours = useMemo(() => {
    const startIndex = (currentPage - 1) * itemsPerPage;
    const endIndex = startIndex + itemsPerPage;
    return filteredAndSortedTours.slice(startIndex, endIndex);
  }, [filteredAndSortedTours, currentPage, itemsPerPage]);

  const handleAddTour = () => {
    setEditingTour(null);
    setShowModal(true);
  };

  const handleEditTour = (tour: Tour) => {
    setEditingTour(tour);
    setShowModal(true);
  };

  const confirmDeleteTour = (tourId: string) => {
    setTourToDelete(tourId);
    setShowConfirmDialog(true);
  };

  const executeDeleteTour = () => {
    if (tourToDelete) {
      onDelete(tourToDelete);
      showSuccess('Tournée supprimée avec succès !');
      setTourToDelete(null);
    }
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    
    const tourData: Omit<Tour, 'user_id' | 'created_at'> = {
      id: editingTour?.id || '', // ID will be generated by Supabase on insert
      date: formData.get('date') as string,
      vehicle_id: formData.get('vehicle_id') as string,
      driver_id: formData.get('driver_id') as string,
      status: formData.get('status') as string,
      fuel_start: formData.get('fuel_start') ? parseInt(formData.get('fuel_start') as string) : null,
      km_start: formData.get('km_start') ? parseInt(formData.get('km_start') as string) : null,
      fuel_end: formData.get('fuel_end') ? parseInt(formData.get('fuel_end') as string) : null,
      km_end: formData.get('km_end') ? parseInt(formData.get('km_end') as string) : null,
      distance: formData.get('distance') ? parseInt(formData.get('distance') as string) : null
    };

    if (editingTour) {
      onUpdate(tourData as Tour);
      showSuccess('Tournée mise à jour avec succès !');
    } else {
      onAdd(tourData);
      showSuccess('Tournée ajoutée avec succès !');
    }
    setShowModal(false);
  };

  const getStatusBadge = (status: string) => {
    const classes = {
      'Planifié': 'bg-blue-100 text-blue-800',
      'En cours': 'bg-yellow-100 text-yellow-800',
      'Terminé': 'bg-green-100 text-green-800',
      'Annulé': 'bg-red-100 text-red-800'
    };
    return `px-3 py-1 text-xs rounded-full font-medium ${classes[status as keyof typeof classes] || 'bg-gray-100 text-gray-800'}`;
  };

  const calculateConsumption = (tour: Tour): string => {
    if (tour.distance && tour.distance > 0 && tour.fuel_start !== null && tour.fuel_end !== null) {
      const fuelConsumed = tour.fuel_start - tour.fuel_end;
      if (fuelConsumed > 0) {
        return ((fuelConsumed / tour.distance) * 100).toFixed(1);
      }
    }
    return '-';
  };

  const handleSort = (column: keyof Tour) => {
    if (sortColumn === column) {
      setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
    } else {
      setSortColumn(column);
      setSortDirection('asc');
    }
  };

  const renderSortIcon = (column: keyof Tour) => {
    if (sortColumn === column) {
      return sortDirection === 'asc' ? <ChevronUp className="w-4 h-4 ml-1" /> : <ChevronDown className="w-4 h-4 ml-1" />;
    }
    return null;
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-4xl font-bold text-gray-800">Suivi des Tournées</h2>
          <Button
            onClick={handleAddTour}
            className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg flex items-center space-x-2 transition-all duration-300"
          >
            <Plus className="w-5 h-5" />
            <span>Nouvelle Tournée</span>
          </Button>
      </div>

      {/* Search Input */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
        <input
          type="text"
          placeholder="Rechercher une tournée par date, véhicule, conducteur ou statut..."
          value={searchTerm}
          onChange={(e) => {
            setSearchTerm(e.target.value);
            setCurrentPage(1); // Reset to first page on new search
          }}
          className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
        />
      </div>

      <div className="bg-white rounded-xl shadow-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider cursor-pointer" onClick={() => handleSort('date')}>
                  <div className="flex items-center">
                    Date {renderSortIcon('date')}
                  </div>
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider cursor-pointer" onClick={() => handleSort('vehicle_id')}>
                  <div className="flex items-center">
                    Véhicule {renderSortIcon('vehicle_id')}
                  </div>
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider cursor-pointer" onClick={() => handleSort('driver_id')}>
                  <div className="flex items-center">
                    Conducteur {renderSortIcon('driver_id')}
                  </div>
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider cursor-pointer" onClick={() => handleSort('status')}>
                  <div className="flex items-center">
                    Statut {renderSortIcon('status')}
                  </div>
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider cursor-pointer" onClick={() => handleSort('fuel_start')}>
                  <div className="flex items-center">
                    Fuel Début {renderSortIcon('fuel_start')}
                  </div>
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider cursor-pointer" onClick={() => handleSort('km_start')}>
                  <div className="flex items-center">
                    Km Début {renderSortIcon('km_start')}
                  </div>
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider cursor-pointer" onClick={() => handleSort('fuel_end')}>
                  <div className="flex items-center">
                    Fuel Fin {renderSortIcon('fuel_end')}
                  </div>
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider cursor-pointer" onClick={() => handleSort('km_end')}>
                  <div className="flex items-center">
                    Km Fin {renderSortIcon('km_end')}
                  </div>
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider cursor-pointer" onClick={() => handleSort('distance')}>
                  <div className="flex items-center">
                    Distance {renderSortIcon('distance')}
                  </div>
                </th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">L/100km</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {currentTours.length === 0 ? (
                <tr>
                  <td colSpan={11} className="px-6 py-4 text-center text-gray-500">
                    Aucune tournée trouvée.
                  </td>
                </tr>
              ) : (
                currentTours.map((tour) => {
                  const vehicle = data.vehicles.find(v => v.id === tour.vehicle_id);
                  const driver = data.drivers.find(d => d.id === tour.driver_id);
                  return (
                    <tr key={tour.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-4 py-4 text-sm text-gray-900">{formatDate(tour.date)}</td>
                      <td className="px-4 py-4 text-sm text-gray-600">{vehicle?.plate || 'N/A'}</td>
                      <td className="px-4 py-4 text-sm text-gray-600">{driver?.name || 'N/A'}</td>
                      <td className="px-4 py-4 text-sm">
                        <span className={getStatusBadge(tour.status)}>{tour.status}</span>
                      </td>
                      <td className="px-4 py-4 text-sm text-center">{tour.fuel_start !== null ? `${tour.fuel_start}%` : '-'}</td>
                      <td className="px-4 py-4 text-sm text-center">{tour.km_start !== null ? tour.km_start.toLocaleString() : '-'}</td>
                      <td className="px-4 py-4 text-sm text-center">{tour.fuel_end !== null ? `${tour.fuel_end}%` : '-'}</td>
                      <td className="px-4 py-4 text-sm text-center">{tour.km_end !== null ? tour.km_end.toLocaleString() : '-'}</td>
                      <td className="px-4 py-4 text-sm font-semibold">{tour.distance !== null ? `${tour.distance.toLocaleString()} km` : '-'}</td>
                      <td className="px-4 py-4 text-sm font-semibold">{calculateConsumption(tour)}</td>
                        <td className="px-4 py-4 text-sm">
                          <div className="flex space-x-2">
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => handleEditTour(tour)}
                              className="text-blue-600 hover:text-blue-900 transition-colors"
                            >
                              <Edit2 className="w-4 h-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => confirmDeleteTour(tour.id)}
                              className="text-red-600 hover:text-red-900 transition-colors"
                            >
                              <Trash2 className="w-4 h-4" />
                            </Button>
                          </div>
                        </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Pagination Controls */}
      {totalPages > 1 && (
        <div className="flex justify-center items-center space-x-2 mt-4">
          <Button
            variant="outline"
            onClick={() => setCurrentPage(prev => Math.max(1, prev - 1))}
            disabled={currentPage === 1}
            className="px-4 py-2 bg-gray-200 rounded-lg hover:bg-gray-300 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Précédent
          </Button>
          {Array.from({ length: totalPages }, (_, i) => i + 1).map(page => (
            <Button
              key={page}
              variant={currentPage === page ? 'default' : 'outline'}
              onClick={() => setCurrentPage(page)}
              className={`px-4 py-2 rounded-lg ${
                currentPage === page ? 'bg-blue-600 text-white' : 'bg-gray-200 hover:bg-gray-300'
              }`}
            >
              {page}
            </Button>
          ))}
          <Button
            variant="outline"
            onClick={() => setCurrentPage(prev => Math.min(totalPages, prev + 1))}
            disabled={currentPage === totalPages}
            className="px-4 py-2 bg-gray-200 rounded-lg hover:bg-gray-300 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Suivant
          </Button>
        </div>
      )}

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-gray-900 bg-opacity-75 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-screen overflow-y-auto">
            <div className="p-8">
              <h3 className="text-2xl font-bold text-gray-800 mb-6">
                {editingTour ? 'Modifier une Tournée' : 'Ajouter une Tournée'}
              </h3>
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Date</label>
                    <input
                      type="date"
                      name="date"
                      defaultValue={editingTour?.date || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                      required
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Statut</label>
                    <select
                      name="status"
                      defaultValue={editingTour?.status || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                      required
                    >
                      <option value="Planifié">Planifié</option>
                      <option value="En cours">En cours</option>
                      <option value="Terminé">Terminé</option>
                      <option value="Annulé">Annulé</option>
                    </select>
                  </div>
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Véhicule</label>
                    <select
                      name="vehicle_id"
                      defaultValue={editingTour?.vehicle_id || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                      required
                    >
                      <option value="">Sélectionner un véhicule</option>
                      {data.vehicles.map(vehicle => (
                        <option key={vehicle.id} value={vehicle.id}>
                          {vehicle.plate} - {vehicle.type}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Conducteur</label>
                    <select
                      name="driver_id"
                      defaultValue={editingTour?.driver_id || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                      required
                    >
                      <option value="">Sélectionner un conducteur</option>
                      {data.drivers.map(driver => (
                        <option key={driver.id} value={driver.id}>
                          {driver.name}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Niveau fuel début (%)</label>
                    <input
                      type="number"
                      name="fuel_start"
                      min="0"
                      max="100"
                      defaultValue={editingTour?.fuel_start || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Km début</label>
                    <input
                      type="number"
                      name="km_start"
                      defaultValue={editingTour?.km_start || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Niveau fuel fin (%)</label>
                    <input
                      type="number"
                      name="fuel_end"
                      min="0"
                      max="100"
                      defaultValue={editingTour?.fuel_end || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Km fin</label>
                    <input
                      type="number"
                      name="km_end"
                      defaultValue={editingTour?.km_end || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2 text-gray-700">Distance (km)</label>
                  <input
                    type="number"
                    name="distance"
                    defaultValue={editingTour?.distance || ''}
                    className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                  />
                </div>

                <div className="flex justify-end space-x-4 mt-8">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setShowModal(false)}
                    className="px-6 py-3 bg-gray-300 hover:bg-gray-400 rounded-lg transition-all duration-300"
                  >
                    Annuler
                  </Button>
                  <Button
                    type="submit"
                    className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-all duration-300"
                  >
                    Sauvegarder
                  </Button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      <ConfirmDialog
        open={showConfirmDialog}
        onOpenChange={setShowConfirmDialog}
        title="Confirmer la suppression"
        description="Êtes-vous sûr de vouloir supprimer cette tournée ? Cette action est irréversible."
        onConfirm={executeDeleteTour}
        confirmText="Supprimer"
        variant="destructive"
      />
    </div>
  );
};

export default Tours;