import React, { useState } from 'react';
import { Plus, Edit2, Trash2 } from 'lucide-react';
import { FleetData, Tour } from '../types';

interface ToursProps {
  data: FleetData;
  onAdd: (tour: Omit<Tour, 'id' | 'user_id' | 'created_at'>) => void;
  onUpdate: (tour: Tour) => void;
  onDelete: (id: string) => void;
}

const Tours: React.FC<ToursProps> = ({ data, onAdd, onUpdate, onDelete }) => {
  const [showModal, setShowModal] = useState(false);
  const [editingTour, setEditingTour] = useState<Tour | null>(null);

  const handleAddTour = () => {
    setEditingTour(null);
    setShowModal(true);
  };

  const handleEditTour = (tour: Tour) => {
    setEditingTour(tour);
    setShowModal(true);
  };

  const handleDeleteTour = (tourId: string) => {
    if (confirm('Êtes-vous sûr de vouloir supprimer cette tournée ?')) {
      onDelete(tourId);
    }
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    
    const tourData: Omit<Tour, 'user_id' | 'created_at'> = {
      id: editingTour?.id || '', // ID will be generated by Supabase on insert
      date: formData.get('date') as string,
      vehicle_id: formData.get('vehicle_id') as string,
      driver_id: formData.get('driver_id') as string,
      status: formData.get('status') as string,
      fuel_start: formData.get('fuel_start') ? parseInt(formData.get('fuel_start') as string) : null,
      km_start: formData.get('km_start') ? parseInt(formData.get('km_start') as string) : null,
      fuel_end: formData.get('fuel_end') ? parseInt(formData.get('fuel_end') as string) : null,
      km_end: formData.get('km_end') ? parseInt(formData.get('km_end') as string) : null,
      distance: formData.get('distance') ? parseInt(formData.get('distance') as string) : null
    };

    if (editingTour) {
      onUpdate(tourData as Tour);
    } else {
      onAdd(tourData);
    }
    setShowModal(false);
  };

  const getStatusBadge = (status: string) => {
    const classes = {
      'Planifié': 'bg-blue-100 text-blue-800',
      'En cours': 'bg-yellow-100 text-yellow-800',
      'Terminé': 'bg-green-100 text-green-800',
      'Annulé': 'bg-red-100 text-red-800'
    };
    return `px-3 py-1 text-xs rounded-full font-medium ${classes[status as keyof typeof classes] || 'bg-gray-100 text-gray-800'}`;
  };

  const calculateConsumption = (tour: Tour): string => {
    if (tour.distance && tour.distance > 0 && tour.fuel_start !== null && tour.fuel_end !== null) {
      const fuelConsumed = tour.fuel_start - tour.fuel_end;
      if (fuelConsumed > 0) {
        return ((fuelConsumed / tour.distance) * 100).toFixed(1);
      }
    }
    return '-';
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-4xl font-bold text-gray-800">Suivi des Tournées</h2>
        <button
          onClick={handleAddTour}
          className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg flex items-center space-x-2 transition-all duration-300"
        >
          <Plus className="w-5 h-5" />
          <span>Nouvelle Tournée</span>
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Date</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Véhicule</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Conducteur</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Statut</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Fuel Début</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Km Début</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Fuel Fin</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Km Fin</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Distance</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">L/100km</th>
                <th className="px-4 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {data.tours.map((tour) => {
                const vehicle = data.vehicles.find(v => v.id === tour.vehicle_id);
                const driver = data.drivers.find(d => d.id === tour.driver_id);
                return (
                  <tr key={tour.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-4 py-4 text-sm text-gray-900">{tour.date}</td>
                    <td className="px-4 py-4 text-sm text-gray-600">{vehicle?.plate || 'N/A'}</td>
                    <td className="px-4 py-4 text-sm text-gray-600">{driver?.name || 'N/A'}</td>
                    <td className="px-4 py-4 text-sm">
                      <span className={getStatusBadge(tour.status)}>{tour.status}</span>
                    </td>
                    <td className="px-4 py-4 text-sm text-center">{tour.fuel_start !== null ? `${tour.fuel_start}%` : '-'}</td>
                    <td className="px-4 py-4 text-sm text-center">{tour.km_start !== null ? tour.km_start.toLocaleString() : '-'}</td>
                    <td className="px-4 py-4 text-sm text-center">{tour.fuel_end !== null ? `${tour.fuel_end}%` : '-'}</td>
                    <td className="px-4 py-4 text-sm text-center">{tour.km_end !== null ? tour.km_end.toLocaleString() : '-'}</td>
                    <td className="px-4 py-4 text-sm font-semibold">{tour.distance !== null ? `${tour.distance.toLocaleString()} km` : '-'}</td>
                    <td className="px-4 py-4 text-sm font-semibold">{calculateConsumption(tour)}</td>
                    <td className="px-4 py-4 text-sm">
                      <div className="flex space-x-2">
                        <button
                          onClick={() => handleEditTour(tour)}
                          className="text-blue-600 hover:text-blue-900 transition-colors"
                        >
                          <Edit2 className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDeleteTour(tour.id)}
                          className="text-red-600 hover:text-red-900 transition-colors"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-gray-900 bg-opacity-75 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-screen overflow-y-auto">
            <div className="p-8">
              <h3 className="text-2xl font-bold text-gray-800 mb-6">
                {editingTour ? 'Modifier une Tournée' : 'Ajouter une Tournée'}
              </h3>
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Date</label>
                    <input
                      type="date"
                      name="date"
                      defaultValue={editingTour?.date || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                      required
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Statut</label>
                    <select
                      name="status"
                      defaultValue={editingTour?.status || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                      required
                    >
                      <option value="Planifié">Planifié</option>
                      <option value="En cours">En cours</option>
                      <option value="Terminé">Terminé</option>
                      <option value="Annulé">Annulé</option>
                    </select>
                  </div>
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Véhicule</label>
                    <select
                      name="vehicle_id"
                      defaultValue={editingTour?.vehicle_id || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                      required
                    >
                      <option value="">Sélectionner un véhicule</option>
                      {data.vehicles.map(vehicle => (
                        <option key={vehicle.id} value={vehicle.id}>
                          {vehicle.plate} - {vehicle.type}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Conducteur</label>
                    <select
                      name="driver_id"
                      defaultValue={editingTour?.driver_id || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                      required
                    >
                      <option value="">Sélectionner un conducteur</option>
                      {data.drivers.map(driver => (
                        <option key={driver.id} value={driver.id}>
                          {driver.name}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Niveau fuel début (%)</label>
                    <input
                      type="number"
                      name="fuel_start"
                      min="0"
                      max="100"
                      defaultValue={editingTour?.fuel_start || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Km début</label>
                    <input
                      type="number"
                      name="km_start"
                      defaultValue={editingTour?.km_start || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Niveau fuel fin (%)</label>
                    <input
                      type="number"
                      name="fuel_end"
                      min="0"
                      max="100"
                      defaultValue={editingTour?.fuel_end || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2 text-gray-700">Km fin</label>
                    <input
                      type="number"
                      name="km_end"
                      defaultValue={editingTour?.km_end || ''}
                      className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2 text-gray-700">Distance (km)</label>
                  <input
                    type="number"
                    name="distance"
                    defaultValue={editingTour?.distance || ''}
                    className="w-full border border-gray-300 rounded-lg px-4 py-3 focus:ring-blue-500 focus:border-blue-500"
                  />
                </div>

                <div className="flex justify-end space-x-4 mt-8">
                  <button
                    type="button"
                    onClick={() => setShowModal(false)}
                    className="px-6 py-3 bg-gray-300 hover:bg-gray-400 rounded-lg transition-all duration-300"
                  >
                    Annuler
                  </button>
                  <button
                    type="submit"
                    className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-all duration-300"
                  >
                    Sauvegarder
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Tours;